### ISSUE TITLE
ERROR: connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by hangyuCho** [jonsoku2/tamastudy#15]
# When i run below command occurred problem.
``` bash
npx env NODE_ENV=test sequelize-cli db:create && npx env NODE_ENV=production sequelize-cli db:create && npx env NODE_ENV=development sequelize-cli db:create
```
# Error log
``` log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'db:create' ]
2 info using npm@6.14.6
3 info using node@v12.14.1
4 verbose run-script [ 'predb:create', 'db:create', 'postdb:create' ]
5 info lifecycle node_api@1.0.0~predb:create: node_api@1.0.0
6 info lifecycle node_api@1.0.0~db:create: node_api@1.0.0
7 verbose lifecycle node_api@1.0.0~db:create: unsafe-perm in lifecycle true
8 verbose lifecycle node_api@1.0.0~db:create: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/1g1204/Documents/git/workspace/project-tama/node_api/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/1g1204/Documents/flutter:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle node_api@1.0.0~db:create: CWD: /Users/1g1204/Documents/git/workspace/project-tama/node_api
10 silly lifecycle node_api@1.0.0~db:create: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npx env NODE_ENV=test sequelize-cli db:create && npx env NODE_ENV=production sequelize-cli db:create && npx env NODE_ENV=development sequelize-cli db:create'
10 silly lifecycle ]
11 silly lifecycle node_api@1.0.0~db:create: Returned: code: 1  signal: null
12 info lifecycle node_api@1.0.0~db:create: Failed to exec db:create script
13 verbose stack Error: node_api@1.0.0 db:create: `npx env NODE_ENV=test sequelize-cli db:create && npx env NODE_ENV=production sequelize-cli db:create && npx env NODE_ENV=development sequelize-cli db:create`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid node_api@1.0.0
15 verbose cwd /Users/1g1204/Documents/git/workspace/project-tama/node_api
16 verbose Darwin 19.6.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "db:create"
18 verbose node v12.14.1
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error node_api@1.0.0 db:create: `npx env NODE_ENV=test sequelize-cli db:create && npx env NODE_ENV=production sequelize-cli db:create && npx env NODE_ENV=development sequelize-cli db:create`
22 error Exit status 1
23 error Failed at the node_api@1.0.0 db:create script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by hangyuCho** [comment]
problem caused by not having Docker?

**Comment by hangyuCho** [comment]
# try 1 :
## 1. install docker client
``` bash
01 brew install Docker
02 docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false
```
## 2. install docker application
['download_link'](https://download.docker.com/mac/stable/Docker.dmg)

**Comment by hangyuCho** [comment]
Try 2 : 
```
01 sequelize --version
zsh: command not found: sequelize
```
